import { gcm } from "@noble/ciphers/aes.js";
import { pbkdf2Async } from "@noble/hashes/pbkdf2.js";
import { sha256 } from "@noble/hashes/sha2.js";

// Define constants for encryption parameters
const ITERATIONS = 100000;
const SALT_LENGTH = 16;
const IV_LENGTH = 12;
const KEY_LENGTH = 32;

/**
 * Derives a cryptographic key from a password string using PBKDF2.
 */
async function deriveKey(password: string, salt: Uint8Array): Promise<Uint8Array> {
  return pbkdf2Async(sha256, new TextEncoder().encode(password), salt, {
    c: ITERATIONS,
    dkLen: KEY_LENGTH,
  });
}

/**
 * Encrypts any serializable data using a password.
 * Returns a Base64 string containing the salt, IV, and ciphertext.
 */
export async function encryptData(
  data: any,
  password: string,
): Promise<string> {
  const enc = new TextEncoder();
  const encodedData = enc.encode(JSON.stringify(data));

  const salt = secureRandomBytes(SALT_LENGTH);
  const iv = secureRandomBytes(IV_LENGTH);

  const aesKey = await deriveKey(password, salt);
  const encryptedBytes = gcm(aesKey, iv).encrypt(encodedData);
  const combined = new Uint8Array(
    salt.length + iv.length + encryptedBytes.length,
  );
  combined.set(salt, 0);
  combined.set(iv, salt.length);
  combined.set(encryptedBytes, salt.length + iv.length);

  // Convert Uint8Array to Base64
  let binary = "";
  const chunkSize = 0x8000;
  for (let i = 0; i < combined.length; i += chunkSize) {
    binary += String.fromCharCode(...combined.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

/**
 * Decrypts a Base64 string generated by encryptData using the correct password.
 * Returns the parsed JSON data.
 */
export async function decryptData(
  encryptedBase64: string,
  password: string,
): Promise<any> {
  try {
    const binary = atob(encryptedBase64);
    const combined = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      combined[i] = binary.charCodeAt(i);
    }

    const salt = combined.subarray(0, SALT_LENGTH);
    const iv = combined.subarray(SALT_LENGTH, SALT_LENGTH + IV_LENGTH);
    const encryptedBytes = combined.subarray(SALT_LENGTH + IV_LENGTH);

    const aesKey = await deriveKey(password, salt);
    const decryptedContent = gcm(aesKey, iv).decrypt(encryptedBytes);

    const dec = new TextDecoder();
    const jsonStr = dec.decode(decryptedContent);
    return JSON.parse(jsonStr);
  } catch (e) {
    throw new Error("Decryption failed. Incorrect password or corrupted data.");
  }
}

function secureRandomBytes(length: number): Uint8Array {
  if (globalThis.crypto?.getRandomValues == null) {
    throw new Error("Secure random number generation is unavailable.");
  }
  return globalThis.crypto.getRandomValues(new Uint8Array(length));
}
